SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_VERTICES = 12
ASTEROID_ROUGHNESS = 0.3
ASTEROID_ROTATE_SPEED = 0.02
ASTEROID_PARTICLES_NUM = 5
ASTEROID_WRAP_OFFSET = 5

PARTICLE_SIZE_MIN = 1
PARTICLE_SIZE_MAX = 4
PARTICLE_SPEED_MIN = 300
PARTICLE_SPEED_MAX = 600

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 4
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_LIVES = 3

SHOT_RADIUS = 2

SCORE_SMALL = 25
SCORE_MEDIUM = 100
SCORE_LARGE = 250

TEXT_SIZE = 24
TEXT_COLOR = (0, 255, 0)

MENU_LINE_HEIGHT = 28